[tool.poetry]
name = "ultra-type"
version = "0.1.0"
description = ""
authors = ["eran.heres@gmail.com <eran.heres@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.2"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
